### PR TITLE
Update text that appears in Google results for "bitclout" 

### PR DESCRIPTION
**Pull request by enmyj**
The current text says what Bitclout isn't but not what it _is_

image

### CODE REVIEW

**Comment by AdityaChaudhary0005** [comment]
I couldn't understand what "Own a piece by buying the BitClout coin $CLOUT" means.
though i would like to see this changed to some better and unique phrase.

**Comment by tijno** [comment]
What about the one in the description meta tag ? 

https://github.com/bitclout/frontend/blob/07db3e8cc022d9918c4f1567e76ef704a1661635/src/index.html#L7

**Comment by AdityaChaudhary0005** [comment]
awesome! short and strait-forward description is better in my opinion

**Comment by teambrixmusic** [comment]
Agree with using the meta.

**Pull request closed without merging**
