### PR TITLE
Add Videso Embed Code

### PR DESCRIPTION
**Pull request by jsonpreet**
Demo Post URL: https://node.deso.org/posts/76bc9161e36d01b9f07c908933979cdd93c011fa3d863a060fd970ef08038155?tab=posts

### CODE REVIEW

**Comment by jsonpreet** [comment]
@lazynina When?

**Comment by jsonpreet** [comment]
Here's Code Repo: https://github.com/jsonpreet/videsoembed

**Comment by jsonpreet** [comment]
hllo

**Comment by jsonpreet** [comment]
Live Demo: https://desoapp.vercel.app/posts/76bc9161e36d01b9f07c908933979cdd93c011fa3d863a060fd970ef08038155?feedTab=Global&tab=posts

**Comment by diamondhands0** [comment]
Hey @jsonpreet ! Just wanted to let you know we're looking at this now (sorry it's taken so long).

There is unfortunately a security issue with allowing arbitrary URLs that could result in phishing attacks on apps. We're discussing this to see if we can approve it. Hopefully that makes sense.

**Comment by jsonpreet** [comment]
> Hey @jsonpreet ! Just wanted to let you know we're looking at this now (sorry it's taken so long).
> 
> 
> 
> There is unfortunately a security issue with allowing arbitrary URLs that could result in phishing attacks on apps. We're discussing this to see if we can approve it. Hopefully that makes sense.

Thank you Sir

**Pull request closed without merging**
